#!/bin/bash 

# clear

ls

# --------------------------------------------------------------

echo 'Compiling '${1}'.f90'

echo '# of arguments passed :'$#


if [ $# -eq 1 ]; then

	echo 'No modules added, compiling '${1}'.f90'
	gfortran -o ${1}.e ${1}.f90

fi	



echo 'There were modules added, compiling with modules'


for i in ${@:2}
do
	a='.f90 '
	b=$b$i$a 
	#echo $b
 	# c=$b$a
done

echo $b



gfortran $b -o ${1}.e ${1}.f90 

echo 'Now, run '${1}'.e: '


./${1}.e

