#!/bin/bash 

# clear

ls

# --------------------------------------------------------------

# echo 'The name of this script is  '$0

# echo $#
# echo $*

N=$#


echo 'Compiling '${1}'.f90'


echo '# of arguments passed :'$#

if [ $# -eq 1 ]; then

	echo 'No modules added, compiling '${!#}'.f90'
	gfortran -o ${!#}.e ${!#}.f90

fi	


echo 'There were modules added, compiling with modules'



for i in ${@:2}
do
	a='.f90 '
	b=$b$i$a 
	#echo $b
 	# c=$b$a
done

echo $b



gfortran $b -o ${1}.e ${1}.f90 

echo 'Now, run '${1}'.e: '


./${1}.e



# syntax compauto <main> <mod1> <mod2> ... <modn> 